
#ifndef __PROTOCOL_H__
#define __PROTOCOL_H__
typedef enum {
    LOGIN_REQUEST,
    REGISTER_REQUEST,
    LOGOUT_REQUEST,
    FIND_IMG_REQUEST,
    FIND_IMG_IN_USERS,
    FILE_WAS_FOUND,
    FILE_WAS_NOT_FOUND,
    SEND_IMGS_TO_USER,
    NO_IMG_FOUND,
    SEND_DONE,
    SEND_IMG_CONTINUE,
    STOP,
    BREAK,
    EXIT_SYS,
    REGISTER_SUCCESS,
    LOGIN_SUCCESS,
    LOGOUT_SUCCESS,
    UPLOAD_SUCCESS,
    INCORRECT_PASSWORD,
    EXISTENCE_USERNAME,   
    LOGIN_FAILED,
    NON_EXISTENCE_USERNAME,
    IS_CURRENTLY_LOGGED
} PROTOCOL;
#endif